server.port=${PORT:8080}
scheduler.id=${SCHEDULER_ID:scheduler-1}
zookeeper.host=${ZOOKEEPER_HOST:localhost:2181}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/distribusync}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
