server.port=8080
scheduler.id=scheduler-1
zookeeper.host=localhost:2181
spring.datasource.url=jdbc:postgresql://localhost:5432/distribusync
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
